/* Toggle Docs — UI translations (English / اردو) + Urdu keyboard data */
'use strict';

const STRINGS = {
  en: {
    appName: 'Toggle Docs',
    tagline: "Pakistan's own docs",
    madeInPk: 'Made in Pakistan',
    untitled: 'Untitled document',
    newDoc: 'New document',
    searchPh: 'Search documents…',
    allDocs: 'All documents',
    starred: 'Starred',
    trash: 'Trash',
    emptyTrash: 'Empty trash',
    localNote: 'Local-first: your documents never leave this device.',
    words: 'words',
    characters: 'characters',
    minRead: 'min read',
    saved: 'Saved',
    saving: 'Saving…',
    star: 'Star',
    unstar: 'Unstar',
    history: 'Version history',
    file: 'File',
    theme: 'Toggle theme',
    langTitle: 'Switch to اردو',
    menuNew: 'New document',
    menuOpen: 'Open / Import…',
    menuExportHtml: 'Export as HTML',
    menuExportTxt: 'Export as TXT',
    menuPrint: 'Print / Save as PDF',
    menuDuplicate: 'Make a copy',
    menuRename: 'Rename',
    menuTrash: 'Move to trash',
    menuBackup: 'Backup everything (JSON)',
    menuRestore: 'Restore backup (JSON)',
    renameTitle: 'Rename document',
    renamePh: 'Document name',
    confirmDeleteTitle: 'Move to trash?',
    confirmDeleteMsg: '"{title}" will be moved to trash. You can restore it later.',
    confirmDeleteForeverTitle: 'Delete forever?',
    confirmDeleteForeverMsg: 'This will permanently delete "{title}". This cannot be undone.',
    confirmEmptyTitle: 'Empty trash?',
    confirmEmptyMsg: 'All documents in trash will be permanently deleted. This cannot be undone.',
    confirmRestoreTitle: 'Restore backup?',
    confirmRestoreMsg: 'Documents from the backup file will replace existing documents with the same ID.',
    cancel: 'Cancel',
    del: 'Delete',
    moveToTrash: 'Move to trash',
    restore: 'Restore',
    historyTitle: 'Version history',
    historyEmpty: 'No saved versions yet. Press Ctrl+S while editing to create a snapshot.',
    historyRestore: 'Restore',
    historyRemove: 'Delete',
    historySize: '{kb} KB',
    restoreVersionMsg: 'Replace the document with this saved version?',
    linkTitle: 'Add link',
    linkPh: 'https://example.com',
    linkTextPh: 'Text (optional)',
    linkApply: 'Apply',
    linkRemove: 'Remove link',
    shortcutsTitle: 'Keyboard shortcuts',
    noDocs: 'No documents yet',
    noDocsHint: 'Click "New document" to get started.',
    trashEmptyNote: 'Trash is empty',
    searchNone: 'No results for "{q}"',
    open: 'Open',
    duplicate: 'Duplicate',
    exportedHtml: 'Exported HTML ✓',
    exportedTxt: 'Exported TXT ✓',
    exportedJson: 'Backup downloaded ✓',
    imported: 'Imported "{title}" ✓',
    importFailed: 'Could not read that file',
    restored: 'Restored ✓',
    backupRestored: 'Backup restored ({n} documents) ✓',
    copiedDoc: 'Copy created ✓',
    trashed: 'Moved to trash',
    deletedForever: 'Deleted forever',
    emptyTrashed: 'Trash emptied',
    starredToast: 'Starred ★',
    unstarredToast: 'Star removed',
    saveNowToast: 'Saved ✓ (version snapshot created)',
    zoomTitle: 'Zoom',
    styleTitle: 'Paragraph style',
    styleNormal: 'Normal text',
    styleH1: 'Heading 1',
    styleH2: 'Heading 2',
    styleH3: 'Heading 3',
    styleQuote: 'Quote',
    styleCode: 'Code block',
    fontTitle: 'Font',
    kbTitle: 'اردو کی بورڈ',
    kbHint: 'Click keys to insert at cursor',
    close: 'Close',
    themeDark: 'Dark theme',
    themeLight: 'Light theme',
    sidebarToggle: 'Toggle sidebar',
    colorText: 'Text colour',
    colorHighlight: 'Highlight colour',
    printHint: 'If no window opened, allow pop-ups for this page.'
  },
  ur: {
    appName: 'ٹاگل ڈاکس',
    tagline: 'پاکستان کا اپنا ڈاکس',
    madeInPk: 'پاکستان میں تیار کردہ',
    untitled: 'بلا عنوان دستاویز',
    newDoc: 'نیا دستاویز',
    searchPh: 'دستاویزات تلاش کریں…',
    allDocs: 'تمام دستاویزات',
    starred: 'پسندیدہ',
    trash: 'ردی',
    emptyTrash: 'ردی خالی کریں',
    localNote: 'مکمل مقامی: آپ کی دستاویزات اسی ڈیوائس پر رہتی ہیں۔',
    words: 'الفاظ',
    characters: 'حروف',
    minRead: 'منٹ مطالعہ',
    saved: 'محفوظ',
    saving: 'محفوظ ہو رہا ہے…',
    star: 'ستارہ لگائیں',
    unstar: 'ستارہ ہٹائیں',
    history: 'ورژن کی تاریخ',
    file: 'فائل',
    theme: 'تھیم تبدیل کریں',
    langTitle: 'Switch to English',
    menuNew: 'نیا دستاویز',
    menuOpen: 'کھولیں / درآمد کریں…',
    menuExportHtml: 'HTML کے طور پر برآمد کریں',
    menuExportTxt: 'TXT کے طور پر برآمد کریں',
    menuPrint: 'پرنٹ / PDF محفوظ کریں',
    menuDuplicate: 'نقل بنائیں',
    menuRename: 'نام تبدیل کریں',
    menuTrash: 'ردی میں ڈالیں',
    menuBackup: 'پورا بیک اپ (JSON)',
    menuRestore: 'بیک اپ بحال کریں (JSON)',
    renameTitle: 'دستاویز کا نام تبدیل کریں',
    renamePh: 'دستاویز کا نام',
    confirmDeleteTitle: 'ردی میں ڈالیں؟',
    confirmDeleteMsg: '"{title}" ردی میں چلی جائے گی۔ آپ بعد میں بحال کر سکتے ہیں۔',
    confirmDeleteForeverTitle: 'ہمیشہ کے لیے حذف کریں؟',
    confirmDeleteForeverMsg: '"{title}" ہمیشہ کے لیے حذف ہو جائے گی۔ یہ عمل واپس نہیں ہو سکتا۔',
    confirmEmptyTitle: 'ردی خالی کریں؟',
    confirmEmptyMsg: 'ردی کی تمام دستاویزات ہمیشہ کے لیے حذف ہو جائیں گی۔ یہ عمل واپس نہیں ہو سکتا۔',
    confirmRestoreTitle: 'بیک اپ بحال کریں؟',
    confirmRestoreMsg: 'بیک اپ فائل کی دستاویزات اسی آئی ڈی کی موجودہ دستاویزات کی جگہ لے لیں گی۔',
    cancel: 'منسوخ کریں',
    del: 'حذف کریں',
    moveToTrash: 'ردی میں ڈالیں',
    restore: 'بحال کریں',
    historyTitle: 'ورژن کی تاریخ',
    historyEmpty: 'ابھی کوئی ورژن محفوظ نہیں۔ لکھتے ہوئے Ctrl+S دبائیں۔',
    historyRestore: 'بحال کریں',
    historyRemove: 'حذف کریں',
    historySize: '{kb} کے بی',
    restoreVersionMsg: 'دستاویز کو اس محفوظ ورژن سے بدل دیں؟',
    linkTitle: 'لنک شامل کریں',
    linkPh: 'https://example.com',
    linkTextPh: 'متن (اختیاری)',
    linkApply: 'لگائیں',
    linkRemove: 'لنک ہٹائیں',
    shortcutsTitle: 'کی بورڈ شارٹ کٹس',
    noDocs: 'ابھی کوئی دستاویز نہیں',
    noDocsHint: 'شروع کرنے کے لیے "نیا دستاویز" پر کلک کریں۔',
    trashEmptyNote: 'ردی خالی ہے',
    searchNone: '"{q}" کے لیے کوئی نتیجہ نہیں',
    open: 'کھولیں',
    duplicate: 'نقل بنائیں',
    exportedHtml: 'HTML برآمد ہو گئی ✓',
    exportedTxt: 'TXT برآمد ہو گئی ✓',
    exportedJson: 'بیک اپ ڈاؤن لوڈ ہو گیا ✓',
    imported: '"{title}" درآمد ہو گئی ✓',
    importFailed: 'یہ فائل پڑھی نہیں جا سکی',
    restored: 'بحال ہو گئی ✓',
    backupRestored: 'بیک اپ بحال ({n} دستاویزات) ✓',
    copiedDoc: 'نقل بن گئی ✓',
    trashed: 'ردی میں چلی گئی',
    deletedForever: 'ہمیشہ کے لیے حذف ہو گئی',
    emptyTrashed: 'ردی خالی ہو گئی',
    starredToast: 'ستارہ لگ گیا ★',
    unstarredToast: 'ستارہ ہٹ گیا',
    saveNowToast: 'محفوظ ✓ (ورژن محفوظ ہو گیا)',
    zoomTitle: 'زوم',
    styleTitle: 'پیراگراف سٹائل',
    styleNormal: 'عام متن',
    styleH1: 'سرخی 1',
    styleH2: 'سرخی 2',
    styleH3: 'سرخی 3',
    styleQuote: 'اقتباس',
    styleCode: 'کوڈ بلاک',
    fontTitle: 'فونٹ',
    kbTitle: 'اردو کی بورڈ',
    kbHint: 'حروف داخل کرنے کے لیے کلید پر کلک کریں',
    close: 'بند کریں',
    themeDark: 'تاریک تھیم',
    themeLight: 'روشن تھیم',
    sidebarToggle: 'سائیڈ بار دکھائیں / چھپائیں',
    colorText: 'متن کا رنگ',
    colorHighlight: 'ہائی لائٹ کا رنگ',
    printHint: 'اگر کوئی ونڈو نہ کھلے تو اس صفحے کے لیے پاپ اپ کی اجازت دیں۔'
  }
};

const KB_ROWS = [
  ['ذ', 'ڑ', 'ژ', 'ٹ', 'ڈ', 'ء', 'ۂ', 'ۃ'],
  ['ق', 'و', 'ع', 'ر', 'ت', 'ی', 'ئ', 'ے'],
  ['پ', 'ہ', 'د', 'ج', 'ک', 'س', 'آ'],
  ['ز', 'ش', 'غ', 'ں', 'ب', 'ل', 'ن', 'م']
];

const KB_SPECIALS = [
  { ch: '،', label: '،' },
  { ch: '۔', label: '۔' },
  { ch: '؟', label: '؟' },
  { ch: '«', label: '«' },
  { ch: '»', label: '»' },
  { ch: '\u200F', label: 'RLM' },
  { ch: '\u200C', label: 'ZWNJ' }
];

const KB_PHRASES = ['السلام علیکم', 'شکریہ', 'پاکستان زندہ باد', 'بہت خوب', 'ماشاء اللہ', 'ان شاء اللہ'];

function t(key, lang) {
  const pack = STRINGS[lang] || STRINGS.en;
  return pack[key] || STRINGS.en[key] || key;
}

function fmt(template, map) {
  let out = String(template || '');
  Object.keys(map || {}).forEach(function (k) {
    out = out.split('{' + k + '}').join(map[k]);
  });
  return out;
}

export const I18N = { STRINGS, KB_ROWS, KB_SPECIALS, KB_PHRASES, t, fmt };
